global:
  prefix: weblog # prefix:metric_name{labels...}
  format: # based on "%h %l %u %t \"%r\" %>s %b"
  - remote_host: label
  - ~ # ignore remote logname; unnamed ignored column
  - remote_user: label
  - timestamp: ~ # ignore timestamp; named ignored column
  - request_header: request_header # special parser that emits the labels "request_http_version", "request_uri" and "request_method"
  - status: label
  - body_bytes_sent: clf_number  # maps a single dash to zero, otherwise behaves like "number"

ssh:
  connection:
    user: random.guy
    password: password123
    file: /var/log/apache/access_log.txt
    connect-timeout: 5  # seconds between connection attempts to hosts
  environments:
    home:
      hosts:
      - 127.0.0.1
    home-2:
      connection: # can be overridden per environment as needed
        user: another.guy
        # password: supasecure
        file: /var/log/apache/access_log.txt
        connect-timeout: 25
      hosts: [nirvana]
